name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Print github workspace
      run: |
          pwd
          echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
          echo "github.workspace = ${{ github.workspace }}"
          echo "pr.ref = ${{github.event.pull_request.head.ref}}"
          echo "github.ref = ${{ github.ref }}"
          
    - uses: actions/checkout@v2
      with:
          path: libngc

    - uses: actions/checkout@v2
      with:
          repository: nhamblenne/ntt
          path: ntt

    - name: Print github workspace
      run: |
          echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
          echo "github.workspace = ${{ github.workspace }}"
          echo "pr.ref = ${{github.event.pull_request.head.ref}}"
          echo "github.ref = ${{ github.ref }}"
    - name: Create Build Environment
      run: cmake -E make_directory $GITHUB_WORKSPACE/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}
      run: |
        pwd
        echo cmake $GITHUB_WORKSPACE/libngc -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DTEST_LIBNGC=ON
        cd build
        cmake $GITHUB_WORKSPACE/libngc -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DTEST_LIBNGC=ON

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: |
           export PATH=$GITHUB_WORKSPACE/ntt/bin:$PATH
           ctest -C $BUILD_TYPE
